# coding: utf-8

"""
    Translator Knowledge Beacon Aggregator API

    This is the Translator Knowledge Beacon Aggregator web service application programming interface (API) that provides integrated access to a pool of knowledge sources publishing concepts and relations through the Translator Knowledge Beacon API. This API is similar to that of the latter mentioned API with the addition of some extra informative endpoints plus session identifier and beacon indices. These latter identifiers are locally assigned numeric indices provided to track the use of specific registered beacons within the aggregator API itself. 

    OpenAPI spec version: 1.1.1
    Contact: richard@starinformatics.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from pprint import pformat
from six import iteritems
import re


class ClientKnowledgeMap(object):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """
    def __init__(self, beacon=None, statements=None):
        """
        ClientKnowledgeMap - a model defined in Swagger

        :param dict swaggerTypes: The key is attribute name
                                  and the value is attribute type.
        :param dict attributeMap: The key is attribute name
                                  and the value is json key in definition.
        """
        self.swagger_types = {
            'beacon': 'int',
            'statements': 'list[ClientKnowledgeMapStatement]'
        }

        self.attribute_map = {
            'beacon': 'beacon',
            'statements': 'statements'
        }

        self._beacon = beacon
        self._statements = statements

    @property
    def beacon(self):
        """
        Gets the beacon of this ClientKnowledgeMap.
        aggregator assigned beacon index identifier 

        :return: The beacon of this ClientKnowledgeMap.
        :rtype: int
        """
        return self._beacon

    @beacon.setter
    def beacon(self, beacon):
        """
        Sets the beacon of this ClientKnowledgeMap.
        aggregator assigned beacon index identifier 

        :param beacon: The beacon of this ClientKnowledgeMap.
        :type: int
        """

        self._beacon = beacon

    @property
    def statements(self):
        """
        Gets the statements of this ClientKnowledgeMap.

        :return: The statements of this ClientKnowledgeMap.
        :rtype: list[ClientKnowledgeMapStatement]
        """
        return self._statements

    @statements.setter
    def statements(self, statements):
        """
        Sets the statements of this ClientKnowledgeMap.

        :param statements: The statements of this ClientKnowledgeMap.
        :type: list[ClientKnowledgeMapStatement]
        """

        self._statements = statements

    def to_dict(self):
        """
        Returns the model properties as a dict
        """
        result = {}

        for attr, _ in iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """
        Returns the string representation of the model
        """
        return pformat(self.to_dict())

    def __repr__(self):
        """
        For `print` and `pprint`
        """
        return self.to_str()

    def __eq__(self, other):
        """
        Returns true if both objects are equal
        """
        if not isinstance(other, ClientKnowledgeMap):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """
        Returns true if both objects are not equal
        """
        return not self == other
