# coding: utf-8

"""
    Translator Knowledge Beacon Aggregator API

    This is the Translator Knowledge Beacon Aggregator web service application programming interface (API) that provides integrated access to a pool of knowledge sources publishing concepts and relations through the Translator Knowledge Beacon API. This API is similar to that of the latter mentioned API with the addition of some extra informative endpoints plus session identifier and beacon indices. These latter identifiers are locally assigned numeric indices provided to track the use of specific registered beacons within the aggregator API itself. 

    OpenAPI spec version: 1.1.1
    Contact: richard@starinformatics.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from pprint import pformat
from six import iteritems
import re


class ClientConceptWithDetailsBeaconEntry(object):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """
    def __init__(self, beacon=None, id=None, synonyms=None, definition=None, details=None):
        """
        ClientConceptWithDetailsBeaconEntry - a model defined in Swagger

        :param dict swaggerTypes: The key is attribute name
                                  and the value is attribute type.
        :param dict attributeMap: The key is attribute name
                                  and the value is json key in definition.
        """
        self.swagger_types = {
            'beacon': 'int',
            'id': 'str',
            'synonyms': 'list[str]',
            'definition': 'str',
            'details': 'list[ClientConceptDetail]'
        }

        self.attribute_map = {
            'beacon': 'beacon',
            'id': 'id',
            'synonyms': 'synonyms',
            'definition': 'definition',
            'details': 'details'
        }

        self._beacon = beacon
        self._id = id
        self._synonyms = synonyms
        self._definition = definition
        self._details = details

    @property
    def beacon(self):
        """
        Gets the beacon of this ClientConceptWithDetailsBeaconEntry.
        Index number of beacon providing these concept details 

        :return: The beacon of this ClientConceptWithDetailsBeaconEntry.
        :rtype: int
        """
        return self._beacon

    @beacon.setter
    def beacon(self, beacon):
        """
        Sets the beacon of this ClientConceptWithDetailsBeaconEntry.
        Index number of beacon providing these concept details 

        :param beacon: The beacon of this ClientConceptWithDetailsBeaconEntry.
        :type: int
        """

        self._beacon = beacon

    @property
    def id(self):
        """
        Gets the id of this ClientConceptWithDetailsBeaconEntry.
        CURIE identifying the specific beacon source concept being described. 

        :return: The id of this ClientConceptWithDetailsBeaconEntry.
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id):
        """
        Sets the id of this ClientConceptWithDetailsBeaconEntry.
        CURIE identifying the specific beacon source concept being described. 

        :param id: The id of this ClientConceptWithDetailsBeaconEntry.
        :type: str
        """

        self._id = id

    @property
    def synonyms(self):
        """
        Gets the synonyms of this ClientConceptWithDetailsBeaconEntry.
        List of synonymous names or identifiers for the concept 

        :return: The synonyms of this ClientConceptWithDetailsBeaconEntry.
        :rtype: list[str]
        """
        return self._synonyms

    @synonyms.setter
    def synonyms(self, synonyms):
        """
        Sets the synonyms of this ClientConceptWithDetailsBeaconEntry.
        List of synonymous names or identifiers for the concept 

        :param synonyms: The synonyms of this ClientConceptWithDetailsBeaconEntry.
        :type: list[str]
        """

        self._synonyms = synonyms

    @property
    def definition(self):
        """
        Gets the definition of this ClientConceptWithDetailsBeaconEntry.
        Concept definition provided by a given beacon 

        :return: The definition of this ClientConceptWithDetailsBeaconEntry.
        :rtype: str
        """
        return self._definition

    @definition.setter
    def definition(self, definition):
        """
        Sets the definition of this ClientConceptWithDetailsBeaconEntry.
        Concept definition provided by a given beacon 

        :param definition: The definition of this ClientConceptWithDetailsBeaconEntry.
        :type: str
        """

        self._definition = definition

    @property
    def details(self):
        """
        Gets the details of this ClientConceptWithDetailsBeaconEntry.

        :return: The details of this ClientConceptWithDetailsBeaconEntry.
        :rtype: list[ClientConceptDetail]
        """
        return self._details

    @details.setter
    def details(self, details):
        """
        Sets the details of this ClientConceptWithDetailsBeaconEntry.

        :param details: The details of this ClientConceptWithDetailsBeaconEntry.
        :type: list[ClientConceptDetail]
        """

        self._details = details

    def to_dict(self):
        """
        Returns the model properties as a dict
        """
        result = {}

        for attr, _ in iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """
        Returns the string representation of the model
        """
        return pformat(self.to_dict())

    def __repr__(self):
        """
        For `print` and `pprint`
        """
        return self.to_str()

    def __eq__(self, other):
        """
        Returns true if both objects are equal
        """
        if not isinstance(other, ClientConceptWithDetailsBeaconEntry):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """
        Returns true if both objects are not equal
        """
        return not self == other
