# coding: utf-8

"""
    Translator Knowledge Beacon Aggregator API

    This is the Translator Knowledge Beacon Aggregator web service application programming interface (API) that provides integrated access to a pool of knowledge sources publishing concepts and relations through the Translator Knowledge Beacon API. This API is similar to that of the latter mentioned API with the addition of some extra informative endpoints plus session identifier and beacon indices. These latter identifiers are locally assigned numeric indices provided to track the use of specific registered beacons within the aggregator API itself. 

    OpenAPI spec version: 1.1.1
    Contact: richard@starinformatics.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from pprint import pformat
from six import iteritems
import re


class ClientClique(object):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """
    def __init__(self, id=None, clique_id=None):
        """
        ClientClique - a model defined in Swagger

        :param dict swaggerTypes: The key is attribute name
                                  and the value is attribute type.
        :param dict attributeMap: The key is attribute name
                                  and the value is json key in definition.
        """
        self.swagger_types = {
            'id': 'str',
            'clique_id': 'str'
        }

        self.attribute_map = {
            'id': 'id',
            'clique_id': 'cliqueId'
        }

        self._id = id
        self._clique_id = clique_id

    @property
    def id(self):
        """
        Gets the id of this ClientClique.
        CURIE identifying the concept whose concept clique is being resolved 

        :return: The id of this ClientClique.
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id):
        """
        Sets the id of this ClientClique.
        CURIE identifying the concept whose concept clique is being resolved 

        :param id: The id of this ClientClique.
        :type: str
        """

        self._id = id

    @property
    def clique_id(self):
        """
        Gets the clique_id of this ClientClique.
        CURIE identifying the equivalent concept clique to which the  input concept CURIE belongs. 

        :return: The clique_id of this ClientClique.
        :rtype: str
        """
        return self._clique_id

    @clique_id.setter
    def clique_id(self, clique_id):
        """
        Sets the clique_id of this ClientClique.
        CURIE identifying the equivalent concept clique to which the  input concept CURIE belongs. 

        :param clique_id: The clique_id of this ClientClique.
        :type: str
        """

        self._clique_id = clique_id

    def to_dict(self):
        """
        Returns the model properties as a dict
        """
        result = {}

        for attr, _ in iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """
        Returns the string representation of the model
        """
        return pformat(self.to_dict())

    def __repr__(self):
        """
        For `print` and `pprint`
        """
        return self.to_str()

    def __eq__(self, other):
        """
        Returns true if both objects are equal
        """
        if not isinstance(other, ClientClique):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """
        Returns true if both objects are not equal
        """
        return not self == other
