# coding: utf-8

"""
    Translator Knowledge Beacon Aggregator API

    This is the Translator Knowledge Beacon Aggregator web service application programming interface (API) that provides integrated access to a pool of knowledge sources publishing concepts and relations through the Translator Knowledge Beacon API. This API is similar to that of the latter mentioned API with the addition of some extra informative endpoints plus session identifier and beacon indices. These latter identifiers are locally assigned numeric indices provided to track the use of specific registered beacons within the aggregator API itself. 

    OpenAPI spec version: 1.1.1
    Contact: richard@starinformatics.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from pprint import pformat
from six import iteritems
import re


class ClientLogEntry(object):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """
    def __init__(self, query_id=None, timestamp=None, beacon=None, query=None, message=None):
        """
        ClientLogEntry - a model defined in Swagger

        :param dict swaggerTypes: The key is attribute name
                                  and the value is attribute type.
        :param dict attributeMap: The key is attribute name
                                  and the value is json key in definition.
        """
        self.swagger_types = {
            'query_id': 'str',
            'timestamp': 'str',
            'beacon': 'int',
            'query': 'str',
            'message': 'str'
        }

        self.attribute_map = {
            'query_id': 'queryId',
            'timestamp': 'timestamp',
            'beacon': 'beacon',
            'query': 'query',
            'message': 'message'
        }

        self._query_id = query_id
        self._timestamp = timestamp
        self._beacon = beacon
        self._query = query
        self._message = message

    @property
    def query_id(self):
        """
        Gets the query_id of this ClientLogEntry.
        session identifier of initiated query 

        :return: The query_id of this ClientLogEntry.
        :rtype: str
        """
        return self._query_id

    @query_id.setter
    def query_id(self, query_id):
        """
        Sets the query_id of this ClientLogEntry.
        session identifier of initiated query 

        :param query_id: The query_id of this ClientLogEntry.
        :type: str
        """

        self._query_id = query_id

    @property
    def timestamp(self):
        """
        Gets the timestamp of this ClientLogEntry.
        timestamp 

        :return: The timestamp of this ClientLogEntry.
        :rtype: str
        """
        return self._timestamp

    @timestamp.setter
    def timestamp(self, timestamp):
        """
        Sets the timestamp of this ClientLogEntry.
        timestamp 

        :param timestamp: The timestamp of this ClientLogEntry.
        :type: str
        """

        self._timestamp = timestamp

    @property
    def beacon(self):
        """
        Gets the beacon of this ClientLogEntry.
        aggregator assigned beacon index identifier 

        :return: The beacon of this ClientLogEntry.
        :rtype: int
        """
        return self._beacon

    @beacon.setter
    def beacon(self, beacon):
        """
        Sets the beacon of this ClientLogEntry.
        aggregator assigned beacon index identifier 

        :param beacon: The beacon of this ClientLogEntry.
        :type: int
        """

        self._beacon = beacon

    @property
    def query(self):
        """
        Gets the query of this ClientLogEntry.
        URL of the API call executed by the aggregator 

        :return: The query of this ClientLogEntry.
        :rtype: str
        """
        return self._query

    @query.setter
    def query(self, query):
        """
        Sets the query of this ClientLogEntry.
        URL of the API call executed by the aggregator 

        :param query: The query of this ClientLogEntry.
        :type: str
        """

        self._query = query

    @property
    def message(self):
        """
        Gets the message of this ClientLogEntry.
        error message 

        :return: The message of this ClientLogEntry.
        :rtype: str
        """
        return self._message

    @message.setter
    def message(self, message):
        """
        Sets the message of this ClientLogEntry.
        error message 

        :param message: The message of this ClientLogEntry.
        :type: str
        """

        self._message = message

    def to_dict(self):
        """
        Returns the model properties as a dict
        """
        result = {}

        for attr, _ in iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """
        Returns the string representation of the model
        """
        return pformat(self.to_dict())

    def __repr__(self):
        """
        For `print` and `pprint`
        """
        return self.to_str()

    def __eq__(self, other):
        """
        Returns true if both objects are equal
        """
        if not isinstance(other, ClientLogEntry):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """
        Returns true if both objects are not equal
        """
        return not self == other
