# coding: utf-8

# flake8: noqa
"""
    Translator Knowledge Beacon Aggregator API

    This is the Translator Knowledge Beacon Aggregator web service application programming interface (API) that provides integrated access to a pool of knowledge sources publishing concepts and relations through the Translator Knowledge Beacon API. This API is similar to that of the latter mentioned API with the addition of some extra informative endpoints plus session identifier and beacon indices. These latter identifiers are locally assigned numeric indices provided to track the use of specific registered beacons within the aggregator API itself.   # noqa: E501

    OpenAPI spec version: 1.1.1
    Contact: richard@starinformatics.com
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

# import models into model package
from kba_client.models.client_beacon_concept_category import ClientBeaconConceptCategory
from kba_client.models.client_beacon_predicate import ClientBeaconPredicate
from kba_client.models.client_clique import ClientClique
from kba_client.models.client_cliques_query import ClientCliquesQuery
from kba_client.models.client_cliques_query_beacon_status import ClientCliquesQueryBeaconStatus
from kba_client.models.client_cliques_query_result import ClientCliquesQueryResult
from kba_client.models.client_cliques_query_status import ClientCliquesQueryStatus
from kba_client.models.client_concept import ClientConcept
from kba_client.models.client_concept_categories_by_beacon import ClientConceptCategoriesByBeacon
from kba_client.models.client_concept_category import ClientConceptCategory
from kba_client.models.client_concept_detail import ClientConceptDetail
from kba_client.models.client_concept_with_details import ClientConceptWithDetails
from kba_client.models.client_concept_with_details_beacon_entry import ClientConceptWithDetailsBeaconEntry
from kba_client.models.client_concepts_query import ClientConceptsQuery
from kba_client.models.client_concepts_query_beacon_status import ClientConceptsQueryBeaconStatus
from kba_client.models.client_concepts_query_result import ClientConceptsQueryResult
from kba_client.models.client_concepts_query_status import ClientConceptsQueryStatus
from kba_client.models.client_knowledge_beacon import ClientKnowledgeBeacon
from kba_client.models.client_knowledge_map import ClientKnowledgeMap
from kba_client.models.client_knowledge_map_object import ClientKnowledgeMapObject
from kba_client.models.client_knowledge_map_predicate import ClientKnowledgeMapPredicate
from kba_client.models.client_knowledge_map_statement import ClientKnowledgeMapStatement
from kba_client.models.client_knowledge_map_subject import ClientKnowledgeMapSubject
from kba_client.models.client_log_entry import ClientLogEntry
from kba_client.models.client_predicate import ClientPredicate
from kba_client.models.client_predicates_by_beacon import ClientPredicatesByBeacon
from kba_client.models.client_statement import ClientStatement
from kba_client.models.client_statement_annotation import ClientStatementAnnotation
from kba_client.models.client_statement_citation import ClientStatementCitation
from kba_client.models.client_statement_details import ClientStatementDetails
from kba_client.models.client_statement_object import ClientStatementObject
from kba_client.models.client_statement_predicate import ClientStatementPredicate
from kba_client.models.client_statement_subject import ClientStatementSubject
from kba_client.models.client_statements_query import ClientStatementsQuery
from kba_client.models.client_statements_query_beacon_status import ClientStatementsQueryBeaconStatus
from kba_client.models.client_statements_query_result import ClientStatementsQueryResult
from kba_client.models.client_statements_query_status import ClientStatementsQueryStatus
