# coding: utf-8

from __future__ import absolute_import
from .base_model_ import Model
from datetime import date, datetime
from typing import List, Dict
from ..util import deserialize_model


class NodeAttribute(Model):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """
    def __init__(self, type: str=None, name: str=None, value: str=None, url: str=None):
        """
        NodeAttribute - a model defined in Swagger

        :param type: The type of this NodeAttribute.
        :type type: str
        :param name: The name of this NodeAttribute.
        :type name: str
        :param value: The value of this NodeAttribute.
        :type value: str
        :param url: The url of this NodeAttribute.
        :type url: str
        """
        self.swagger_types = {
            'type': str,
            'name': str,
            'value': str,
            'url': str
        }

        self.attribute_map = {
            'type': 'type',
            'name': 'name',
            'value': 'value',
            'url': 'url'
        }

        self._type = type
        self._name = name
        self._value = value
        self._url = url

    @classmethod
    def from_dict(cls, dikt) -> 'NodeAttribute':
        """
        Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Node_attribute of this NodeAttribute.
        :rtype: NodeAttribute
        """
        return deserialize_model(dikt, cls)

    @property
    def type(self) -> str:
        """
        Gets the type of this NodeAttribute.
        Entity type of this attribute

        :return: The type of this NodeAttribute.
        :rtype: str
        """
        return self._type

    @type.setter
    def type(self, type: str):
        """
        Sets the type of this NodeAttribute.
        Entity type of this attribute

        :param type: The type of this NodeAttribute.
        :type type: str
        """

        self._type = type

    @property
    def name(self) -> str:
        """
        Gets the name of this NodeAttribute.
        Formal name of the attribute

        :return: The name of this NodeAttribute.
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name: str):
        """
        Sets the name of this NodeAttribute.
        Formal name of the attribute

        :param name: The name of this NodeAttribute.
        :type name: str
        """

        self._name = name

    @property
    def value(self) -> str:
        """
        Gets the value of this NodeAttribute.
        Value of the attribute

        :return: The value of this NodeAttribute.
        :rtype: str
        """
        return self._value

    @value.setter
    def value(self, value: str):
        """
        Sets the value of this NodeAttribute.
        Value of the attribute

        :param value: The value of this NodeAttribute.
        :type value: str
        """

        self._value = value

    @property
    def url(self) -> str:
        """
        Gets the url of this NodeAttribute.
        A URL corresponding to this attribute

        :return: The url of this NodeAttribute.
        :rtype: str
        """
        return self._url

    @url.setter
    def url(self, url: str):
        """
        Sets the url of this NodeAttribute.
        A URL corresponding to this attribute

        :param url: The url of this NodeAttribute.
        :type url: str
        """

        self._url = url

