# coding: utf-8

from __future__ import absolute_import
from swagger_server.bio.knowledge.server.model.feedback import Feedback
from .base_model_ import Model
from datetime import date, datetime
from typing import List, Dict
from ..util import deserialize_model


class ResponseFeedback(Model):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """
    def __init__(self, feedback_list: List[Feedback]=None):
        """
        ResponseFeedback - a model defined in Swagger

        :param feedback_list: The feedback_list of this ResponseFeedback.
        :type feedback_list: List[Feedback]
        """
        self.swagger_types = {
            'feedback_list': List[Feedback]
        }

        self.attribute_map = {
            'feedback_list': 'feedback_list'
        }

        self._feedback_list = feedback_list

    @classmethod
    def from_dict(cls, dikt) -> 'ResponseFeedback':
        """
        Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The ResponseFeedback of this ResponseFeedback.
        :rtype: ResponseFeedback
        """
        return deserialize_model(dikt, cls)

    @property
    def feedback_list(self) -> List[Feedback]:
        """
        Gets the feedback_list of this ResponseFeedback.

        :return: The feedback_list of this ResponseFeedback.
        :rtype: List[Feedback]
        """
        return self._feedback_list

    @feedback_list.setter
    def feedback_list(self, feedback_list: List[Feedback]):
        """
        Sets the feedback_list of this ResponseFeedback.

        :param feedback_list: The feedback_list of this ResponseFeedback.
        :type feedback_list: List[Feedback]
        """

        self._feedback_list = feedback_list

